### ISSUE TITLE
[FEAT] Run integration tests w/o Rabbitmq

### ISSUE THREAD

**Issue by ihor-sviziev** [graycoreio/github-actions-magento2#64]
# :bulb: Feature request

## The Desired Behavior
 I never saw integration tests that depend on RabbitMQ. Since there is a way to install Magento w/o it - I think it's a good idea to speed up the integration test.

Currently, I'm not using these actions because of this.
here is my config preparation for integration tests:
```yml
      - name: Replace Configuration Settings for env
        working-directory: ./magento2/dev/tests/integration/etc
        run: |
          cat install-config-mysql.php.dist \
            | sed "s/'db-host' => 'localhost'/'db-host' => '127.0.0.1'/" \
            | sed "s/'db-user' => 'root'/'db-user' => 'user'/" \
            | sed "s/'db-password' => '123123q'/'db-password' => 'password'/" \
            | sed "s/'elasticsearch-host' => 'localhost'/'elasticsearch-host' => '127.0.0.1'/" \
            | sed '/amqp/d' > install-config-mysql.php
```
## Environment

<pre><code>
Magento version: X.Y.Z 
PHP Version version: X.Y.Z 

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This is tangentially related to #50

**Comment by damienwebdev** [comment]
Moved to https://github.com/mage-os/github-actions/issues/14
