### ISSUE TITLE
[FEAT] Add support for cs2pr to `magento2-coding-standard` `phpcs` Github Actions

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/github-actions-magento2#71]
# :bulb: Feature request

## Feature Name
Coding Standard

## The Desired Behavior
@ihor-sviziev requested that we leverage `cs2pr` to add info the Github Action

https://github.com/graycoreio/github-actions-magento2/issues/27#issuecomment-1271250642

## Your Use Case
Nicer code review :)

## Prior Work
https://github.com/graycoreio/github-actions-magento2/issues/27#issuecomment-1271250642

**Comment by gowrizrh** [comment]
Could this be assigned to me please

**Comment by damienwebdev** [comment]
Closing in favor of https://github.com/mage-os/github-actions/issues/17
